#pragma once

#define ID_ICON               102
#define IMAGE_SPLASH          300

#define IMAGE_LOGO            301

#define DW_MOTD               302
#define DW_PLAYLISTS          303
#define DW_SURVEYS            304
#define DW_TASKCONFIG         305
#define DW_PLAYERDATA         306

#define TLS_DLL               307

#define DW_PUBLISHER_VARIABLES_MP       309
#define DW_PUBLISHER_VARIABLES_MM_GAME  310
#define DW_PUBLISHER_VARIABLES_MM_HUB   311
#define DW_PUBLISHER_VARIABLES_MM_PARTY 312
#define DW_PUBLISHER_VARIABLES_QOS      313

#define DW_MARKETPLACE_SKUS             314
#define DW_MARKETPLACE_PRODUCTS         315
#define DW_MARKETPLACE_CATALOG_MANIFEST 316

#define DW_ACHIEVEMENT_OFFERS           317

#define DW_ZOMBIE_CONSUMABLE_REFERENCES 318

#define LAUNCHER_DOCUMENT      400
#define LAUNCHER_STYLES        401
#define LAUNCHER_TITLE_FONT    402
#define LAUNCHER_BODY_FONT     403
#define LAUNCHER_BACKGROUND    404
#define LAUNCHER_SINGLEPLAYER  405
#define LAUNCHER_MULTIPLAYER   406
#define LAUNCHER_ZOMBIES       407
#define LAUNCHER_LICENSES      408
#define LAUNCHER_WORDMARK      409
